# Generated by Django 5.0.2 on 2024-06-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
